### ISSUE TITLE
Pattern issue still exists (7.1)

### ISSUE THREAD

**Issue by Frank071** [foxyproxy/firefox-extension#33]
It seems that v7.1 has not solved #32:
![afbeelding](https://user-images.githubusercontent.com/807403/65700763-78e1a400-e080-11e9-89ac-4de2d4e27a7e.png)
I tried loading the current git version but that seemed not to solve the issue either.

**Comment by ericjung** [comment]
Can you please send or post your FoxyProxy settings? Export them to a file, open the file, and change any private data. Thank you.

**Comment by ericjung** [comment]
This should be fixed in 7.2, just released. Can you try it? Tell Firefox to force update by going to about:addons in the address bar, clicking the "gear icon" then, "Check for Updates"

**Comment by EchoDev** [comment]
There still seems to be an issue with patterns I think. I came from version 6.6.2 and in Version 7.2 the log doesn't even seem to work for me.

My settings (edited urls, ports etc.)
```
{
  "logging": {
    "size": 100,
    "active": true
  },
  "mode": "patterns",
  "sync": false,
  "zdazoo1504616299287": {
    "title": "proxyname",
    "type": 3,
    "color": "#66cc66",
    "address": "edited-address",
    "port": 1234,
    "proxyDNS": true,
    "active": true,
    "whitePatterns": [
      {
        "active": true,
        "pattern": "*.examplesite.com:*",
        "type": 1,
        "protocols": 1,
        "title": "example"
      }
    ],
    "blackPatterns": [
      {
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:localhost|127\\.\\d+\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1,
        "active": true,
        "title": "localhost URLs"
      },
      {
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?(?:192\\.168\\.\\d+\\.\\d+|10\\.\\d+\\.\\d+\\.\\d+|172\\.(?:1[6789]|2[0-9]|3[01])\\.\\d+\\.\\d+)(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1,
        "active": true,
        "title": "internal IP addresses"
      },
      {
        "pattern": "^(?:[^:@/]+(?::[^@/]+)?@)?[\\w-]+(?::\\d+)?(?:/.*)?$",
        "type": 2,
        "protocols": 1,
        "active": true,
        "title": "localhost hostnames"
      }
    ],
    "index": 0
  }
}
```

**Comment by Frank071** [comment]
I attached the current configuration. I updated to 7.2, but the problem persists.

[FoxyProxy Standard_2019-09-26.json.txt](https://github.com/foxyproxy/firefox-extension/files/3659906/FoxyProxy.Standard_2019-09-26.json.txt)

**Comment by ericjung** [comment]
I'm sorry, but I need more info. Right now all I have is:

1. Pattern issue still exists (which one? the [linked issue](https://github.com/foxyproxy/firefox-extension/issues/32) has nothing to do with patterns  as far as I can tell. it has to do with SSL proxy servers.
2. There still seems to be an issue with patterns I think
3. The log doesn't even seem to work for me.
4. I updated to 7.2, but the problem persists.

What **exactly** is the issue? I have 2 settings files -- that's great, and I do indeed thank both Frank071 and EchoDev.

But now what do I do to reproduce the problem? Can you give me an example of something that is broken? for instance, you could say "I set _FoxyProxy to Use Enabled Proxies by Patterns and Order_, visited iplocation.net and expected to see IP address 123.123.123.123 but instead saw 222.222.22.222.

Thank you.

**Comment by Geremia** [comment]
I get this issue, too, in 7.2. Patterns do not make their proxy trigger when "Use Enabled Proxies By Patterns and Order" is set. Proxies do work when I manually choose a specific proxy.

**Comment by Frank071** [comment]
> I'm sorry, but I need more info. Right now all I have is:

OK. As far as I can see currently *all* URLs (http and https) get "pattern matched" to the first enabled proxy of the configuration, regardless of the contents of the url. As you can see from my screenshot in the OP requests to 10.2.2.254 and to a firefox host are routed through the first enabled proxy as if the URL matched 10.1.11.* .
This is obviously with the FP setting 'Use enabled proxy by patterns and order"

**Comment by ericjung** [comment]
Thank you for the details. Now I understand I also notice that @Frank071  and @EchoDev are both using SOCKS proxy servers. I'm wondering if this is restricted to SOCKS since I'm not seeing it with HTTP/SSL proxy servers. @Geremia , are you also using SOCKS proxy servers?

**Comment by ericjung** [comment]
> I'm wondering if this is restricted to SOCKS
@EchoDev do you have any white patterns that are IP addresses? Dont see any in what you pasted but I want to be sure. Are you using SOCKS proxy servers?

**Comment by ericjung** [comment]
Thank you. I found the problem and am fixing now.

**Comment by ericjung** [comment]
@Frank071 , @Geremia , @EchoDev : can you please test the fix? Here's how:

1. Download and unzip https://github.com/foxyproxy/firefox-extension/archive/7.3.zip
2. Export your FoxyProxy settings to a file (Use the `Export` feature). Then either uninstall existing FoxyProxy.... or create a new Firefox profile by starting Firefox on the command-line with `firefox -p`  (if you want to create a new profile, be sure Firefox is completely closed first).
3. Go to about:debugging#/runtime/this-firefox in the address bar
4. Click `Load Temporary Add-on...` and select the file `manifest.json` in the files you unzipped in step #1. It is in the `src/` subdirectory.
5. If you're using the same Firefox profile as before, all your settings should be there. If it's a new profile, use the `Import` feature to import the settings you exported in step #1 

Would really appreciate your feedback as soon as possible.

--Eric

**Comment by 5j9** [comment]
Installing the temporary extension (as instructed in previous comment by Eric) solved the issue for me.

**Comment by ericjung** [comment]
@5j9 thanks!

I believe this issue is fixed in version 7.3. That version is now submitted to https://addons.mozilla.org. Since FoxyProxy is a recommended add-on by Mozilla, humans manually review all changes. So you can't get it from https://addons.mozilla.org until Mozilla releases it.

I will try to update this issue when Mozilla releases 7.3. You can then force an update instead of waiting for Mozilla to push it to you. Instructions to force update:

1. In firefox, go to about:addons in the address bar
2. Click the "gear" icon and select "Check for Updates"

Thanks, everyone, for your amazing help! I really appreciate it and now wish FoxyProxy had been on github earlier.

**Comment by Frank071** [comment]
I can confirm that this version works for me. (Sorry for the delay, in my timezone the night has just ended :-) )

**Comment by ericjung** [comment]
The new version is now available:

1. In firefox, go to about:addons in the address bar
2. Click the "gear" icon and select "Check for Updates"
